---
title: "Social Analytics - Tweets"
author: "Pik Shan Yiu"
date: "4/6/2019"
output: html_document
---


```{r}
library(openssl)
library(httpuv)
library(twitteR)
library(httr)
library(tidyverse)
library(topicmodels)
library(tm)
library(wordcloud)
library(tidytext)
library(ggplot2)
library(plotly)
library(ggthemes)
library(reshape2)
library(scales)
library(BTM)
library(RColorBrewer)
```

### Setting up Twitter API
```{r}
consumer_key <- "e38YMvwaYVvA0XnovOeSgsER3"
consumer_secret <- "0WAIn6bc1VTZhJ7gq1ILCOxXJWb9kryg8J9ZRD3llS0nSW2jvd"
access_token <-  "917771335388016640-i08AohTDSNvlzCOxODeNTf26Z1q7ftg"
access_secret <- "HtiRz3K3fRqpX9w3xeYt6cR5QYDoBQ4NDuU2X7djlFNja"

setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
```

### Retrieving Tweets
```{r}
get_glossier <- searchTwitter("glossier", n = 3200, lang = "en")
get_milk <- searchTwitter("milk makeup", n = 3200, lang = "en") #Only 414 tweets are returned compared to glossier
get_glossier_offi <- userTimeline(user = "glossier", n = 3200, includeRts = T)
get_milk_offi <- userTimeline(user = "milkmakeup", n = 3200, includeRts = T)
get_glossier_ori <- strip_retweets(get_glossier)
```
### Converting to DF
```{r}
gloss_df <- twListToDF(glossier) 
gloss_offi_df <- twListToDF(glossier_offi)
milk_df <- twListToDF(milk)
milk_offi_df <- twListToDF(milk_offi)
```


```{r}
df_drop <- c("favorited", "truncated","replyToSID", "replyToUID", "longitude", "latitude") #Removing unwanted columns & duplicate
gloss_df <- gloss_df[, !names(gloss_df) %in% df_drop]
gloss_df <- gloss_df[gloss_df$screenName != 'glossier', ] #Removing @glossier's tweets
milk_df <- milk_df[, !names(milk_df) %in% df_drop]
milk_df <- milk_df[milk_df$screenName != 'milkmakeup', ] #Removing @milk's tweets
milk_offi_df <- milk_offi_df[, !names(milk_offi_df) %in% df_drop]
gloss_offi_df <- gloss_offi_df[, !names(gloss_offi_df) %in% df_drop]
milk_offi_df$brand = "Milk Official"
gloss_offi_df$brand = "Glossier Official"
gloss_df$brand = "Glossier"
milk_df$brand = "Milk"
```

#### Who's More Active?
```{r}
g1 <- rbind(gloss_offi_df, milk_offi_df) %>% mutate(date = trunc(as.Date(created), "day")) %>% group_by(date, brand) %>% summarize(counts = sum(table(id))) %>% filter(date > "2018-03-26") %>% ggplot(aes(x = date, y = counts, color = brand)) + geom_line() + labs(x="Date", y="Number of Tweets") + ggtitle('Number of Tweets Across Time') + theme_tufte() + scale_color_manual(values = c("pink1", "seagreen3")) + theme(plot.title = element_text(hjust = 0.5, face='bold', size=15), text=element_text(family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) 
ggplotly(g1) %>% layout(legend = list(x = 0.8, y = 0.9))
```

#### Retweet
```{r}
ggplotly(rbind(gloss_offi_df, milk_offi_df) %>% group_by(brand) %>% summarize(Retweet = sum(isRetweet), Selftweet = sum(table(isRetweet)) - Retweet) %>% melt() %>% ggplot(aes(x = brand, y = value, fill = variable)) + geom_bar(position = 'fill', stat = "identity") + scale_fill_manual(values = c("sienna1", "lightskyblue")) + labs(x="", y="% Retweets") + ggtitle('Who Retweets More?') + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) + scale_y_continuous(labels = percent_format()) + coord_flip()) %>% layout(legend = list(x = 0.8, y = 1.3))
```

#### Reply 
```{r}
ggplotly(rbind(gloss_offi_df, milk_offi_df) %>% group_by(brand) %>% summarize(Reply = sum(!is.na(replyToSN)), Nonreply = sum(is.na(replyToSN))) %>% melt() %>% ggplot(aes(x = brand, y = value, fill = variable)) + geom_bar(position = 'fill', stat = "identity") + scale_fill_manual(values = c("sienna1", "lightskyblue")) + labs(x="", y="% Reply") + ggtitle("Let's Talk") + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) + scale_y_continuous(labels = percent_format()) + coord_flip()) %>% layout(legend = list(x = 0.8, y = 1.3))
```

#### What are they replying about? 
```{r}
gloss_reply <- gloss_offi_df %>% filter(is.na(replyToSN) == FALSE)
milk_reply <- milk_offi_df %>% filter(is.na(replyToSN) == FALSE)
gloss_reply_corpus <- VCorpus(VectorSource(gloss_reply$text))
milk_reply_corpus <- VCorpus(VectorSource(milk_reply$text))
removelinks <- function(x){gsub("http\\S+\\s*", "", x)}
removebrand <- function(x){gsub("(G|g)lossi(er|ers) | (M|m)ilk", "", x)}
removeat <- function(x){gsub("@\\w+", "", x)}
removeemoji <- function(x){gsub('\\p{So}|\\p{Cn}', "", x, perl = TRUE)}
clean_corpus <- function(corpus) {
      corpus <- tm_map(corpus, content_transformer(removelinks))
      corpus <- tm_map(corpus, content_transformer(removebrand))
      corpus <- tm_map(corpus, content_transformer(removeat))
      corpus <- tm_map(corpus, content_transformer(removeemoji))
      corpus <- tm_map(corpus, content_transformer(removeNumbers))
      corpus <- tm_map(corpus, content_transformer(removePunctuation))
      corpus <- tm_map(corpus, content_transformer(tolower))
      corpus <- tm_map(corpus, content_transformer(removeWords), c(stopwords("en"))) 
      corpus <- tm_map(corpus, content_transformer(stripWhitespace))
                       return(corpus)}
gloss_reply_clean <- clean_corpus(gloss_reply_corpus)
milk_reply_clean <- clean_corpus(milk_reply_corpus)
```

```{r}
pal1 <- brewer.pal(20, 'Reds')
pal2 <- brewer.pal(20, 'BuGn')
layout(matrix(c(1, 2, 3, 4), nrow=2, ncol=2), heights=c(1, 2))
par(mar=c(0.01,0.01,0.01,0.01))
plot.new()
text(x=0.5, y=0.5, "Glossier's Top Words", cex=1.5, family = "Courier", col = 'pink1')
set.seed(2103)
wordcloud(gloss_reply_clean, max.words = 20, random.order = FALSE, scale = c(3.5, 2), colors = pal1, family = "Courier") #wordcloud for a sneak peek
plot.new()
text(x=0.5, y=0.5, "Milk's Top Words", cex=1.5, family = "Courier", col = 'seagreen2')
set.seed(2103)
wordcloud(milk_reply_clean, max.words = 20, random.order = FALSE,  scale = c(3.5, 2), colors = pal2, family = "Courier") 
```

#### Reply Topics 
```{r}
dtm <- function(corpus) {
  corpus <- DocumentTermMatrix(corpus)
  rowTotals <- apply(corpus, 1, sum)
corpus <- corpus[rowTotals > 0, ]
 return(corpus)
}
gloss_reply_dtm <- dtm(gloss_reply_clean)
gloss_reply_lda <- LDA(gloss_reply_dtm, k = 4, method = "VEM", control = NULL)
gloss_reply_topics <- tidy(gloss_reply_lda, matrix = "beta")
gloss_reply_topterms <- gloss_reply_topics %>% group_by(topic) %>% top_n(10, beta) %>% ungroup() %>% arrange(topic, -beta)
gloss_reply_topterms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()

```


#### Customers' voice
```{r}
gloss_unique <- unique(gloss_df$text)
glossier_corpus <- VCorpus(VectorSource(gloss_unique))
glossier_clean <- clean_corpus(glossier_corpus)
glossier_tdm <- DocumentTermMatrix(glossier_clean)
glossier_tdm_tfidf <- weightTfIdf(glossier_tdm)
```