---
title: "Social Analytics - Tweets"
author: "Pik Shan Yiu"
date: "4/6/2019"
output: html_document
---


```{r}
library(openssl)
library(httpuv)
library(twitteR)
library(httr)
library(tidyverse)
library(topicmodels)
library(tm)
library(wordcloud)
library(tidytext)
library(ggplot2)
library(plotly)
library(ggthemes)
library(reshape2)
library(scales)
library(RColorBrewer)
library(syuzhet)
```

### Setting up Twitter API
```{r}
consumer_key <- "e38YMvwaYVvA0XnovOeSgsER3"
consumer_secret <- "0WAIn6bc1VTZhJ7gq1ILCOxXJWb9kryg8J9ZRD3llS0nSW2jvd"
access_token <-  "917771335388016640-i08AohTDSNvlzCOxODeNTf26Z1q7ftg"
access_secret <- "HtiRz3K3fRqpX9w3xeYt6cR5QYDoBQ4NDuU2X7djlFNja"

setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
```

### Retrieving Tweets
```{r}
get_glossier <- searchTwitter("glossier", n = 3200, lang = "en")
get_milk <- searchTwitter("milk makeup", n = 3200, lang = "en") #Only 414 tweets are returned compared to glossier
get_glossier_offi <- userTimeline(user = "glossier", n = 3200, includeRts = T)
get_milk_offi <- userTimeline(user = "milkmakeup", n = 3200, includeRts = T)
get_glossier_ori <- strip_retweets(get_glossier)
```
### Converting to DF
```{r}
gloss_df <- twListToDF(glossier) 
gloss_offi_df <- twListToDF(glossier_offi)
milk_df <- twListToDF(milk)
milk_offi_df <- twListToDF(milk_offi)
```


```{r}
df_drop <- c("favorited", "truncated","replyToSID", "replyToUID", "longitude", "latitude") #Removing unwanted columns & duplicate
gloss_df <- gloss_df[, !names(gloss_df) %in% df_drop]
gloss_df <- gloss_df[gloss_df$screenName != 'glossier', ] #Removing @glossier's tweets
milk_df <- milk_df[, !names(milk_df) %in% df_drop]
milk_df <- milk_df[milk_df$screenName != 'milkmakeup', ] #Removing @milk's tweets
milk_offi_df <- milk_offi_df[, !names(milk_offi_df) %in% df_drop]
gloss_offi_df <- gloss_offi_df[, !names(gloss_offi_df) %in% df_drop]
milk_offi_df$brand = "Milk Official"
gloss_offi_df$brand = "Glossier Official"
gloss_df$brand = "Glossier"
milk_df$brand = "Milk"
```

#### Who's More Active?
```{r}
g1 <- rbind(gloss_offi_df, milk_offi_df) %>% mutate(date = trunc(as.Date(created), "day")) %>% group_by(date, brand) %>% summarize(counts = sum(table(id))) %>% filter(date > "2018-03-26") %>% ggplot(aes(x = date, y = counts, color = brand)) + geom_line() + labs(x="Date", y="Number of Tweets") + ggtitle('Number of Tweets Across Time') + theme_tufte() + scale_color_manual(values = c("pink1", "seagreen3")) + theme(plot.title = element_text(hjust = 0.5, face='bold', size=15), text=element_text(family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) 
ggplotly(g1) %>% layout(legend = list(x = 0.8, y = 0.9))
```

Who's got more volumne
```{r}
g2 <- rbind(gloss_df, milk_df) %>% mutate(date = trunc(as.Date(created), "day")) %>% group_by(date, brand) %>% summarize(counts = sum(table(id))) %>% filter(date > "2019-03-31") %>% ggplot(aes(x = date, y = counts, color = brand)) + geom_line() + labs(x="Date", y="Number of Tweets") + ggtitle('Number of Conversations Across Time') + theme_tufte() + scale_color_manual(values = c("pink1", "seagreen3")) + theme(plot.title = element_text(hjust = 0.5, face='bold', size=15), text=element_text(family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) 
ggplotly(g2) %>% layout(legend = list(x = 0.8, y = 0.9))
```
#### Retweet
```{r}
ggplotly(rbind(gloss_offi_df, milk_offi_df) %>% group_by(brand) %>% summarize(Retweet = sum(isRetweet), Selftweet = sum(table(isRetweet)) - Retweet) %>% melt() %>% ggplot(aes(x = brand, y = value, fill = variable)) + geom_bar(position = 'fill', stat = "identity") + scale_fill_manual(values = c("sienna1", "lightskyblue")) + labs(x="", y="% Retweets") + ggtitle('Who Retweets More?') + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) + scale_y_continuous(labels = percent_format()) + coord_flip()) %>% layout(legend = list(x = 0.8, y = 1.3))
```

#### Reply 
```{r}
ggplotly(rbind(gloss_offi_df, milk_offi_df) %>% group_by(brand) %>% summarize(Reply = sum(!is.na(replyToSN)), Nonreply = sum(is.na(replyToSN))) %>% melt() %>% ggplot(aes(x = brand, y = value, fill = variable)) + geom_bar(position = 'fill', stat = "identity") + scale_fill_manual(values = c("sienna1", "lightskyblue")) + labs(x="", y="% Reply") + ggtitle("Let's Talk") + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Garamond")) + theme(legend.position = "top") + theme(legend.title=element_blank()) + scale_y_continuous(labels = percent_format()) + coord_flip()) %>% layout(legend = list(x = 0.8, y = 1.3))
```

#### What are they replying about? 
```{r}
gloss_reply <- gloss_offi_df %>% filter(is.na(replyToSN) == FALSE)
milk_reply <- milk_offi_df %>% filter(is.na(replyToSN) == FALSE)
gloss_reply_corpus <- VCorpus(VectorSource(gloss_reply$text))
milk_reply_corpus <- VCorpus(VectorSource(milk_reply$text))
removelinks <- function(x){gsub("http\\S+\\s*", "", x)}
removebrand <- function(x){gsub("(G|g)lossi(er|ers) | (M|m)ilk", "", x)}
removeat <- function(x){gsub("@\\w+", "", x)}
removeemoji <- function(x){gsub('\\p{So}|\\p{Cn}', "", x, perl = TRUE)}
clean_corpus <- function(corpus) {
      corpus <- tm_map(corpus, content_transformer(removelinks))
      corpus <- tm_map(corpus, content_transformer(removebrand))
      corpus <- tm_map(corpus, content_transformer(removeat))
      corpus <- tm_map(corpus, content_transformer(removeemoji))
      corpus <- tm_map(corpus, content_transformer(removeNumbers))
      corpus <- tm_map(corpus, content_transformer(removePunctuation))
      corpus <- tm_map(corpus, content_transformer(tolower))
      corpus <- tm_map(corpus, content_transformer(removeWords), c(stopwords("en"))) 
      corpus <- tm_map(corpus, content_transformer(stripWhitespace))
                       return(corpus)}
gloss_reply_clean <- clean_corpus(gloss_reply_corpus)
milk_reply_clean <- clean_corpus(milk_reply_corpus)
```

```{r}
pal1 <- brewer.pal(20, 'Reds')
pal2 <- brewer.pal(20, 'BuGn')
layout(matrix(c(1, 2, 3, 4), nrow=2, ncol=2), heights=c(1, 2))
par(mar=c(0.01,0.01,0.01,0.01))
plot.new()
text(x=0.5, y=0.5, "Glossier's Top Words", cex=1.5, family = "Courier", col = 'pink1')
set.seed(2103)
wordcloud(gloss_reply_clean, max.words = 20, random.order = FALSE, scale = c(3.5, 2), colors = pal1, family = "Courier") #wordcloud for a sneak peek
plot.new()
text(x=0.5, y=0.5, "Milk's Top Words", cex=1.5, family = "Courier", col = 'seagreen2')
set.seed(2103)
wordcloud(milk_reply_clean, max.words = 20, random.order = FALSE,  scale = c(3.5, 2), colors = pal2, family = "Courier") 
```


#### Customers' voice
```{r}
gloss_unique <- unique(gloss_df$text)
milk_unique <- unique(milk_df$text)
gloss_sentiment <- get_nrc_sentiment((gloss_unique))
milk_sentiment <- get_nrc_sentiment(milk_unique)
sentimentscore_glossier <- data.frame(colSums(gloss_sentiment[,]))
sentimentscore_milk <- data.frame(colSums(milk_sentiment[,]))
names(sentimentscore_glossier) <- "Score"
names(sentimentscore_milk) <- "Score"
sentimentscore_glossier <-  cbind("sentiment" = rownames(sentimentscore_glossier), sentimentscore_glossier)
sentimentscore_milk <-  cbind("sentiment" = rownames(sentimentscore_milk), sentimentscore_milk)
ggplot(data = sentimentscore_glossier, aes(x = sentiment, y = Score)) + geom_bar(aes(fill = sentiment), stat = "identity") +  labs(x="Sentiment", y="Score") + ggtitle("Tweets Sentiment on Glossier") + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Courier")) + theme(legend.position = "none")
ggplot(data = sentimentscore_milk, aes(x = sentiment, y = Score)) + geom_bar(aes(fill = sentiment), stat = "identity") +  labs(x="Sentiment", y="Score") + ggtitle("Tweets Sentiment on Milk Makeup") + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Courier")) + theme(legend.position = "none")
```

#### Shit Talk...Or Not?
```{r}
gloss_sentiment$bad <- rowSums(gloss_sentiment[, c(1,3,4,6,9)])
gloss_sentiment <- rowid_to_column(gloss_sentiment, "ID")
gloss_negative <- arrange(gloss_sentiment, desc(gloss_sentiment$bad))[1:20,]$ID
gloss_negative <- unlist(gloss_negative)
gloss_unique <- rowid_to_column(as.data.frame(gloss_unique), "ID")
names(gloss_unique)[2] <- "text"
gloss_unique[gloss_unique$ID %in% gloss_negative, ]$text
```

```{r}
milk_sentiment$bad <- rowSums(milk_sentiment[, c(1,3,4,6,9)])
milk_sentiment <- rowid_to_column(milk_sentiment, "ID")
milk_negative <- arrange(milk_sentiment, desc(milk_sentiment$bad))[1:20,]$ID
milk_negative <- unlist(milk_negative)
milk_unique <- rowid_to_column(as.data.frame(milk_unique), "ID")
names(milk_unique)[2] <- "text"
milk_unique[milk_unique$ID %in% milk_negative, ]$text
```


#Glossier's Miami Store
```{r}
miami <- gloss_df$text[str_detect(gloss_df$text, "miami")]
miami_sentiment <- get_nrc_sentiment((miami))
sentimentscore_miami <- data.frame(colSums(miami_sentiment[,]))
names(sentimentscore_miami) <- "Score"
sentimentscore_miami <-  cbind("sentiment" = rownames(sentimentscore_miami), sentimentscore_miami)
ggplot(data = sentimentscore_miami, aes(x = sentiment, y = Score)) + geom_bar(aes(fill = sentiment), stat = "identity") +  labs(x="Sentiment", y="Score") + ggtitle("Tweets Sentiment on Glossier's Miami Store") + theme_tufte() + theme(plot.title=element_text(hjust=0.45, vjust=0.5, face='bold', size=15, family="Courier")) + theme(legend.position = "none")
```

```{r}
miami_sentiment$bad <- rowSums(miami_sentiment[, c(1,3,4,6,9)])
miami_sentiment <- rowid_to_column(miami_sentiment, "ID")
miami_negative <- arrange(miami_sentiment, desc(miami_sentiment$bad))[1:10,]$ID
miami_negative <- unlist(miami_negative)
miami <- rowid_to_column(as.data.frame(miami), "ID")
names(miami)[2] <- "text"
miami_bad <- miami[miami$ID %in% miami_negative, ]$text
```